### ISSUE TITLE
Problem at installation.

### ISSUE THREAD

**Issue by ivanperazzo** [Sama34/OUGC-Unlocked-Content-Log#1]
Hi Omar, im having an issue with the install:
`Fatal error: Uncaught Error: Call to undefined function OUGCUnlockedContentLog\Admin\_install() in /home/mumakers/public_html/inc/plugins/ougc_unlocked_content_log.php:73 Stack trace: #0 /home/mumakers/public_html/admin/modules/config/plugins.php(426): ougc_unlocked_content_log_install() #1 /home/mumakers/public_html/admin/index.php(824): require('/home/mumakers/...') #2 {main} thrown in /home/mumakers/public_html/inc/plugins/ougc_unlocked_content_log.php on line 73`

Any tip on what could be causing it? Thanks

**Comment by Sama34** [comment]
Hi, sorry for the late response.

I know there is people using this so I'm surprised no one noticed this.

**Comment by ivanperazzo** [comment]
> Hi, sorry for the late response.
> 
> I know there is people using this so I'm surprised no one noticed this.

Honestly, for MyBB related 3 days its a veeeery fast response ^^. Thanks for solving it. Keep up the good work ^^
